// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hubspot-go/deals/models/components"
)

type DeleteCrmV3ObjectsDealsDealIDArchiveSecurity struct {
	Oauth2      *string `security:"scheme,type=oauth2,name=Authorization"`
	PrivateApps *string `security:"scheme,type=apiKey,subtype=header,name=private-app"`
}

func (d *DeleteCrmV3ObjectsDealsDealIDArchiveSecurity) GetOauth2() *string {
	if d == nil {
		return nil
	}
	return d.Oauth2
}

func (d *DeleteCrmV3ObjectsDealsDealIDArchiveSecurity) GetPrivateApps() *string {
	if d == nil {
		return nil
	}
	return d.PrivateApps
}

type DeleteCrmV3ObjectsDealsDealIDArchiveRequest struct {
	DealID string `pathParam:"style=simple,explode=false,name=dealId"`
}

func (d *DeleteCrmV3ObjectsDealsDealIDArchiveRequest) GetDealID() string {
	if d == nil {
		return ""
	}
	return d.DealID
}

type DeleteCrmV3ObjectsDealsDealIDArchiveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (d *DeleteCrmV3ObjectsDealsDealIDArchiveResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteCrmV3ObjectsDealsDealIDArchiveResponse) GetBody() []byte {
	if d == nil {
		return nil
	}
	return d.Body
}
