// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hubspot-go/deals/internal/utils"
	"github.com/speakeasy-sdks/hubspot-go/deals/models/components"
)

type GetCrmV3ObjectsDealsDealIDGetByIDSecurity struct {
	Oauth2      *string `security:"scheme,type=oauth2,name=Authorization"`
	PrivateApps *string `security:"scheme,type=apiKey,subtype=header,name=private-app"`
}

func (g *GetCrmV3ObjectsDealsDealIDGetByIDSecurity) GetOauth2() *string {
	if g == nil {
		return nil
	}
	return g.Oauth2
}

func (g *GetCrmV3ObjectsDealsDealIDGetByIDSecurity) GetPrivateApps() *string {
	if g == nil {
		return nil
	}
	return g.PrivateApps
}

type GetCrmV3ObjectsDealsDealIDGetByIDRequest struct {
	DealID string `pathParam:"style=simple,explode=false,name=dealId"`
	// A comma separated list of the properties to be returned in the response. If any of the specified properties are not present on the requested object(s), they will be ignored.
	Properties []string `queryParam:"style=form,explode=true,name=properties"`
	// A comma separated list of the properties to be returned along with their history of previous values. If any of the specified properties are not present on the requested object(s), they will be ignored.
	PropertiesWithHistory []string `queryParam:"style=form,explode=true,name=propertiesWithHistory"`
	// A comma separated list of object types to retrieve associated IDs for. If any of the specified associations do not exist, they will be ignored.
	Associations []string `queryParam:"style=form,explode=true,name=associations"`
	// Whether to return only results that have been archived.
	Archived *bool `default:"false" queryParam:"style=form,explode=true,name=archived"`
	// The name of a property whose values are unique for this object type
	IDProperty *string `queryParam:"style=form,explode=true,name=idProperty"`
}

func (g GetCrmV3ObjectsDealsDealIDGetByIDRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCrmV3ObjectsDealsDealIDGetByIDRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"dealId"}); err != nil {
		return err
	}
	return nil
}

func (g *GetCrmV3ObjectsDealsDealIDGetByIDRequest) GetDealID() string {
	if g == nil {
		return ""
	}
	return g.DealID
}

func (g *GetCrmV3ObjectsDealsDealIDGetByIDRequest) GetProperties() []string {
	if g == nil {
		return nil
	}
	return g.Properties
}

func (g *GetCrmV3ObjectsDealsDealIDGetByIDRequest) GetPropertiesWithHistory() []string {
	if g == nil {
		return nil
	}
	return g.PropertiesWithHistory
}

func (g *GetCrmV3ObjectsDealsDealIDGetByIDRequest) GetAssociations() []string {
	if g == nil {
		return nil
	}
	return g.Associations
}

func (g *GetCrmV3ObjectsDealsDealIDGetByIDRequest) GetArchived() *bool {
	if g == nil {
		return nil
	}
	return g.Archived
}

func (g *GetCrmV3ObjectsDealsDealIDGetByIDRequest) GetIDProperty() *string {
	if g == nil {
		return nil
	}
	return g.IDProperty
}

type GetCrmV3ObjectsDealsDealIDGetByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	SimplePublicObjectWithAssociations *components.SimplePublicObjectWithAssociations
	Body                               []byte
}

func (g *GetCrmV3ObjectsDealsDealIDGetByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCrmV3ObjectsDealsDealIDGetByIDResponse) GetSimplePublicObjectWithAssociations() *components.SimplePublicObjectWithAssociations {
	if g == nil {
		return nil
	}
	return g.SimplePublicObjectWithAssociations
}

func (g *GetCrmV3ObjectsDealsDealIDGetByIDResponse) GetBody() []byte {
	if g == nil {
		return nil
	}
	return g.Body
}
