// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hubspot-go/deals/internal/utils"
	"github.com/speakeasy-sdks/hubspot-go/deals/models/components"
)

type GetCrmV3ObjectsDealsGetPageSecurity struct {
	Oauth2      *string `security:"scheme,type=oauth2,name=Authorization"`
	PrivateApps *string `security:"scheme,type=apiKey,subtype=header,name=private-app"`
}

func (o *GetCrmV3ObjectsDealsGetPageSecurity) GetOauth2() *string {
	if o == nil {
		return nil
	}
	return o.Oauth2
}

func (o *GetCrmV3ObjectsDealsGetPageSecurity) GetPrivateApps() *string {
	if o == nil {
		return nil
	}
	return o.PrivateApps
}

type GetCrmV3ObjectsDealsGetPageRequest struct {
	// The maximum number of results to display per page.
	Limit *int `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// The paging cursor token of the last successfully read resource will be returned as the `paging.next.after` JSON property of a paged response containing more results.
	After *string `queryParam:"style=form,explode=true,name=after"`
	// A comma separated list of the properties to be returned in the response. If any of the specified properties are not present on the requested object(s), they will be ignored.
	Properties []string `queryParam:"style=form,explode=true,name=properties"`
	// A comma separated list of the properties to be returned along with their history of previous values. If any of the specified properties are not present on the requested object(s), they will be ignored. Usage of this parameter will reduce the maximum number of objects that can be read by a single request.
	PropertiesWithHistory []string `queryParam:"style=form,explode=true,name=propertiesWithHistory"`
	// A comma separated list of object types to retrieve associated IDs for. If any of the specified associations do not exist, they will be ignored.
	Associations []string `queryParam:"style=form,explode=true,name=associations"`
	// Whether to return only results that have been archived.
	Archived *bool `default:"false" queryParam:"style=form,explode=true,name=archived"`
}

func (g GetCrmV3ObjectsDealsGetPageRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCrmV3ObjectsDealsGetPageRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetCrmV3ObjectsDealsGetPageRequest) GetLimit() *int {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetCrmV3ObjectsDealsGetPageRequest) GetAfter() *string {
	if o == nil {
		return nil
	}
	return o.After
}

func (o *GetCrmV3ObjectsDealsGetPageRequest) GetProperties() []string {
	if o == nil {
		return nil
	}
	return o.Properties
}

func (o *GetCrmV3ObjectsDealsGetPageRequest) GetPropertiesWithHistory() []string {
	if o == nil {
		return nil
	}
	return o.PropertiesWithHistory
}

func (o *GetCrmV3ObjectsDealsGetPageRequest) GetAssociations() []string {
	if o == nil {
		return nil
	}
	return o.Associations
}

func (o *GetCrmV3ObjectsDealsGetPageRequest) GetArchived() *bool {
	if o == nil {
		return nil
	}
	return o.Archived
}

type GetCrmV3ObjectsDealsGetPageResponse struct {
	HTTPMeta components.HTTPMetadata
	// successful operation
	CollectionResponseSimplePublicObjectWithAssociationsForwardPaging *components.CollectionResponseSimplePublicObjectWithAssociationsForwardPaging
	Body                                                              []byte
}

func (o *GetCrmV3ObjectsDealsGetPageResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetCrmV3ObjectsDealsGetPageResponse) GetCollectionResponseSimplePublicObjectWithAssociationsForwardPaging() *components.CollectionResponseSimplePublicObjectWithAssociationsForwardPaging {
	if o == nil {
		return nil
	}
	return o.CollectionResponseSimplePublicObjectWithAssociationsForwardPaging
}

func (o *GetCrmV3ObjectsDealsGetPageResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}
