// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hubspot-go/deals/models/components"
)

type PatchCrmV3ObjectsDealsDealIDUpdateSecurity struct {
	Oauth2      *string `security:"scheme,type=oauth2,name=Authorization"`
	PrivateApps *string `security:"scheme,type=apiKey,subtype=header,name=private-app"`
}

func (p *PatchCrmV3ObjectsDealsDealIDUpdateSecurity) GetOauth2() *string {
	if p == nil {
		return nil
	}
	return p.Oauth2
}

func (p *PatchCrmV3ObjectsDealsDealIDUpdateSecurity) GetPrivateApps() *string {
	if p == nil {
		return nil
	}
	return p.PrivateApps
}

type PatchCrmV3ObjectsDealsDealIDUpdateRequest struct {
	DealID string `pathParam:"style=simple,explode=false,name=dealId"`
	// The name of a property whose values are unique for this object type
	IDProperty              *string                            `queryParam:"style=form,explode=true,name=idProperty"`
	SimplePublicObjectInput components.SimplePublicObjectInput `request:"mediaType=application/json"`
}

func (p *PatchCrmV3ObjectsDealsDealIDUpdateRequest) GetDealID() string {
	if p == nil {
		return ""
	}
	return p.DealID
}

func (p *PatchCrmV3ObjectsDealsDealIDUpdateRequest) GetIDProperty() *string {
	if p == nil {
		return nil
	}
	return p.IDProperty
}

func (p *PatchCrmV3ObjectsDealsDealIDUpdateRequest) GetSimplePublicObjectInput() components.SimplePublicObjectInput {
	if p == nil {
		return components.SimplePublicObjectInput{}
	}
	return p.SimplePublicObjectInput
}

type PatchCrmV3ObjectsDealsDealIDUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	SimplePublicObject *components.SimplePublicObject
	Body               []byte
}

func (p *PatchCrmV3ObjectsDealsDealIDUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PatchCrmV3ObjectsDealsDealIDUpdateResponse) GetSimplePublicObject() *components.SimplePublicObject {
	if p == nil {
		return nil
	}
	return p.SimplePublicObject
}

func (p *PatchCrmV3ObjectsDealsDealIDUpdateResponse) GetBody() []byte {
	if p == nil {
		return nil
	}
	return p.Body
}
