// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hubspot-go/deals/models/components"
)

type PatchCrmV3ObjectsDealsDealIDUpdateSecurity struct {
	Oauth2      *string `security:"scheme,type=oauth2,name=Authorization"`
	PrivateApps *string `security:"scheme,type=apiKey,subtype=header,name=private-app"`
}

func (o *PatchCrmV3ObjectsDealsDealIDUpdateSecurity) GetOauth2() *string {
	if o == nil {
		return nil
	}
	return o.Oauth2
}

func (o *PatchCrmV3ObjectsDealsDealIDUpdateSecurity) GetPrivateApps() *string {
	if o == nil {
		return nil
	}
	return o.PrivateApps
}

type PatchCrmV3ObjectsDealsDealIDUpdateRequest struct {
	DealID                  string                             `pathParam:"style=simple,explode=false,name=dealId"`
	SimplePublicObjectInput components.SimplePublicObjectInput `request:"mediaType=application/json"`
	// The name of a property whose values are unique for this object type
	IDProperty *string `queryParam:"style=form,explode=true,name=idProperty"`
}

func (o *PatchCrmV3ObjectsDealsDealIDUpdateRequest) GetDealID() string {
	if o == nil {
		return ""
	}
	return o.DealID
}

func (o *PatchCrmV3ObjectsDealsDealIDUpdateRequest) GetSimplePublicObjectInput() components.SimplePublicObjectInput {
	if o == nil {
		return components.SimplePublicObjectInput{}
	}
	return o.SimplePublicObjectInput
}

func (o *PatchCrmV3ObjectsDealsDealIDUpdateRequest) GetIDProperty() *string {
	if o == nil {
		return nil
	}
	return o.IDProperty
}

type PatchCrmV3ObjectsDealsDealIDUpdateResponse struct {
	HTTPMeta components.HTTPMetadata
	// successful operation
	SimplePublicObject *components.SimplePublicObject
	Body               []byte
}

func (o *PatchCrmV3ObjectsDealsDealIDUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PatchCrmV3ObjectsDealsDealIDUpdateResponse) GetSimplePublicObject() *components.SimplePublicObject {
	if o == nil {
		return nil
	}
	return o.SimplePublicObject
}

func (o *PatchCrmV3ObjectsDealsDealIDUpdateResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}
