// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hubspot-go/deals/models/components"
)

type PostCrmV3ObjectsDealsBatchCreateCreateSecurity struct {
	Oauth2      *string `security:"scheme,type=oauth2,name=Authorization"`
	PrivateApps *string `security:"scheme,type=apiKey,subtype=header,name=private-app"`
}

func (p *PostCrmV3ObjectsDealsBatchCreateCreateSecurity) GetOauth2() *string {
	if p == nil {
		return nil
	}
	return p.Oauth2
}

func (p *PostCrmV3ObjectsDealsBatchCreateCreateSecurity) GetPrivateApps() *string {
	if p == nil {
		return nil
	}
	return p.PrivateApps
}

type PostCrmV3ObjectsDealsBatchCreateCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	BatchResponseSimplePublicObject *components.BatchResponseSimplePublicObject
	// multiple statuses
	BatchResponseSimplePublicObjectWithErrors *components.BatchResponseSimplePublicObjectWithErrors
	Body                                      []byte
}

func (p *PostCrmV3ObjectsDealsBatchCreateCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostCrmV3ObjectsDealsBatchCreateCreateResponse) GetBatchResponseSimplePublicObject() *components.BatchResponseSimplePublicObject {
	if p == nil {
		return nil
	}
	return p.BatchResponseSimplePublicObject
}

func (p *PostCrmV3ObjectsDealsBatchCreateCreateResponse) GetBatchResponseSimplePublicObjectWithErrors() *components.BatchResponseSimplePublicObjectWithErrors {
	if p == nil {
		return nil
	}
	return p.BatchResponseSimplePublicObjectWithErrors
}

func (p *PostCrmV3ObjectsDealsBatchCreateCreateResponse) GetBody() []byte {
	if p == nil {
		return nil
	}
	return p.Body
}
