// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hubspot-go/deals/models/components"
)

type PostCrmV3ObjectsDealsBatchArchiveArchiveSecurity struct {
	Oauth2      *string `security:"scheme,type=oauth2,name=Authorization"`
	PrivateApps *string `security:"scheme,type=apiKey,subtype=header,name=private-app"`
}

func (p *PostCrmV3ObjectsDealsBatchArchiveArchiveSecurity) GetOauth2() *string {
	if p == nil {
		return nil
	}
	return p.Oauth2
}

func (p *PostCrmV3ObjectsDealsBatchArchiveArchiveSecurity) GetPrivateApps() *string {
	if p == nil {
		return nil
	}
	return p.PrivateApps
}

type PostCrmV3ObjectsDealsBatchArchiveArchiveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (p *PostCrmV3ObjectsDealsBatchArchiveArchiveResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostCrmV3ObjectsDealsBatchArchiveArchiveResponse) GetBody() []byte {
	if p == nil {
		return nil
	}
	return p.Body
}
