// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hubspot-go/deals/models/components"
)

type PostCrmV3ObjectsDealsMergeMergeSecurity struct {
	Oauth2      *string `security:"scheme,type=oauth2,name=Authorization"`
	PrivateApps *string `security:"scheme,type=apiKey,subtype=header,name=private-app"`
}

func (p *PostCrmV3ObjectsDealsMergeMergeSecurity) GetOauth2() *string {
	if p == nil {
		return nil
	}
	return p.Oauth2
}

func (p *PostCrmV3ObjectsDealsMergeMergeSecurity) GetPrivateApps() *string {
	if p == nil {
		return nil
	}
	return p.PrivateApps
}

type PostCrmV3ObjectsDealsMergeMergeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	SimplePublicObject *components.SimplePublicObject
	Body               []byte
}

func (p *PostCrmV3ObjectsDealsMergeMergeResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostCrmV3ObjectsDealsMergeMergeResponse) GetSimplePublicObject() *components.SimplePublicObject {
	if p == nil {
		return nil
	}
	return p.SimplePublicObject
}

func (p *PostCrmV3ObjectsDealsMergeMergeResponse) GetBody() []byte {
	if p == nil {
		return nil
	}
	return p.Body
}
