// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hubspot-go/deals/models/components"
)

type PostCrmV3ObjectsDealsGdprDeletePurgeSecurity struct {
	Oauth2      *string `security:"scheme,type=oauth2,name=Authorization"`
	PrivateApps *string `security:"scheme,type=apiKey,subtype=header,name=private-app"`
}

func (p *PostCrmV3ObjectsDealsGdprDeletePurgeSecurity) GetOauth2() *string {
	if p == nil {
		return nil
	}
	return p.Oauth2
}

func (p *PostCrmV3ObjectsDealsGdprDeletePurgeSecurity) GetPrivateApps() *string {
	if p == nil {
		return nil
	}
	return p.PrivateApps
}

type PostCrmV3ObjectsDealsGdprDeletePurgeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (p *PostCrmV3ObjectsDealsGdprDeletePurgeResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostCrmV3ObjectsDealsGdprDeletePurgeResponse) GetBody() []byte {
	if p == nil {
		return nil
	}
	return p.Body
}
