// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hubspot-go/deals/models/components"
)

type PostCrmV3ObjectsDealsSearchDoSearchSecurity struct {
	Oauth2      *string `security:"scheme,type=oauth2,name=Authorization"`
	PrivateApps *string `security:"scheme,type=apiKey,subtype=header,name=private-app"`
}

func (p *PostCrmV3ObjectsDealsSearchDoSearchSecurity) GetOauth2() *string {
	if p == nil {
		return nil
	}
	return p.Oauth2
}

func (p *PostCrmV3ObjectsDealsSearchDoSearchSecurity) GetPrivateApps() *string {
	if p == nil {
		return nil
	}
	return p.PrivateApps
}

type PostCrmV3ObjectsDealsSearchDoSearchResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	CollectionResponseWithTotalSimplePublicObjectForwardPaging *components.CollectionResponseWithTotalSimplePublicObjectForwardPaging
	Body                                                       []byte
}

func (p *PostCrmV3ObjectsDealsSearchDoSearchResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostCrmV3ObjectsDealsSearchDoSearchResponse) GetCollectionResponseWithTotalSimplePublicObjectForwardPaging() *components.CollectionResponseWithTotalSimplePublicObjectForwardPaging {
	if p == nil {
		return nil
	}
	return p.CollectionResponseWithTotalSimplePublicObjectForwardPaging
}

func (p *PostCrmV3ObjectsDealsSearchDoSearchResponse) GetBody() []byte {
	if p == nil {
		return nil
	}
	return p.Body
}
