// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AssociatedID struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

func (a *AssociatedID) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AssociatedID) GetType() string {
	if a == nil {
		return ""
	}
	return a.Type
}
