// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type AssociationCategory string

const (
	AssociationCategoryHubspotDefined    AssociationCategory = "HUBSPOT_DEFINED"
	AssociationCategoryUserDefined       AssociationCategory = "USER_DEFINED"
	AssociationCategoryIntegratorDefined AssociationCategory = "INTEGRATOR_DEFINED"
)

func (e AssociationCategory) ToPointer() *AssociationCategory {
	return &e
}
func (e *AssociationCategory) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "HUBSPOT_DEFINED":
		fallthrough
	case "USER_DEFINED":
		fallthrough
	case "INTEGRATOR_DEFINED":
		*e = AssociationCategory(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AssociationCategory: %v", v)
	}
}

type AssociationSpec struct {
	AssociationCategory AssociationCategory `json:"associationCategory"`
	AssociationTypeID   int                 `json:"associationTypeId"`
}

func (a *AssociationSpec) GetAssociationCategory() AssociationCategory {
	if a == nil {
		return AssociationCategory("")
	}
	return a.AssociationCategory
}

func (a *AssociationSpec) GetAssociationTypeID() int {
	if a == nil {
		return 0
	}
	return a.AssociationTypeID
}
