// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type BatchInputSimplePublicObjectInputForCreate struct {
	Inputs []SimplePublicObjectInputForCreate `json:"inputs"`
}

func (o *BatchInputSimplePublicObjectInputForCreate) GetInputs() []SimplePublicObjectInputForCreate {
	if o == nil {
		return []SimplePublicObjectInputForCreate{}
	}
	return o.Inputs
}
