// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BatchInputSimplePublicObjectID struct {
	Inputs []SimplePublicObjectID `json:"inputs"`
}

func (b *BatchInputSimplePublicObjectID) GetInputs() []SimplePublicObjectID {
	if b == nil {
		return []SimplePublicObjectID{}
	}
	return b.Inputs
}
