// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type BatchInputSimplePublicObjectBatchInput struct {
	Inputs []SimplePublicObjectBatchInput `json:"inputs"`
}

func (o *BatchInputSimplePublicObjectBatchInput) GetInputs() []SimplePublicObjectBatchInput {
	if o == nil {
		return []SimplePublicObjectBatchInput{}
	}
	return o.Inputs
}
