// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/hubspot-go/deals/internal/utils"
	"time"
)

type BatchResponseSimplePublicObjectWithErrorsStatus string

const (
	BatchResponseSimplePublicObjectWithErrorsStatusPending    BatchResponseSimplePublicObjectWithErrorsStatus = "PENDING"
	BatchResponseSimplePublicObjectWithErrorsStatusProcessing BatchResponseSimplePublicObjectWithErrorsStatus = "PROCESSING"
	BatchResponseSimplePublicObjectWithErrorsStatusCanceled   BatchResponseSimplePublicObjectWithErrorsStatus = "CANCELED"
	BatchResponseSimplePublicObjectWithErrorsStatusComplete   BatchResponseSimplePublicObjectWithErrorsStatus = "COMPLETE"
)

func (e BatchResponseSimplePublicObjectWithErrorsStatus) ToPointer() *BatchResponseSimplePublicObjectWithErrorsStatus {
	return &e
}
func (e *BatchResponseSimplePublicObjectWithErrorsStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PENDING":
		fallthrough
	case "PROCESSING":
		fallthrough
	case "CANCELED":
		fallthrough
	case "COMPLETE":
		*e = BatchResponseSimplePublicObjectWithErrorsStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BatchResponseSimplePublicObjectWithErrorsStatus: %v", v)
	}
}

type BatchResponseSimplePublicObjectWithErrors struct {
	CompletedAt time.Time                                       `json:"completedAt"`
	NumErrors   *int                                            `json:"numErrors,omitempty"`
	RequestedAt *time.Time                                      `json:"requestedAt,omitempty"`
	StartedAt   time.Time                                       `json:"startedAt"`
	Links       map[string]string                               `json:"links,omitempty"`
	Results     []SimplePublicObject                            `json:"results"`
	Errors      []StandardError                                 `json:"errors,omitempty"`
	Status      BatchResponseSimplePublicObjectWithErrorsStatus `json:"status"`
}

func (b BatchResponseSimplePublicObjectWithErrors) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BatchResponseSimplePublicObjectWithErrors) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"completedAt", "startedAt", "results", "status"}); err != nil {
		return err
	}
	return nil
}

func (b *BatchResponseSimplePublicObjectWithErrors) GetCompletedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.CompletedAt
}

func (b *BatchResponseSimplePublicObjectWithErrors) GetNumErrors() *int {
	if b == nil {
		return nil
	}
	return b.NumErrors
}

func (b *BatchResponseSimplePublicObjectWithErrors) GetRequestedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.RequestedAt
}

func (b *BatchResponseSimplePublicObjectWithErrors) GetStartedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.StartedAt
}

func (b *BatchResponseSimplePublicObjectWithErrors) GetLinks() map[string]string {
	if b == nil {
		return nil
	}
	return b.Links
}

func (b *BatchResponseSimplePublicObjectWithErrors) GetResults() []SimplePublicObject {
	if b == nil {
		return []SimplePublicObject{}
	}
	return b.Results
}

func (b *BatchResponseSimplePublicObjectWithErrors) GetErrors() []StandardError {
	if b == nil {
		return nil
	}
	return b.Errors
}

func (b *BatchResponseSimplePublicObjectWithErrors) GetStatus() BatchResponseSimplePublicObjectWithErrorsStatus {
	if b == nil {
		return BatchResponseSimplePublicObjectWithErrorsStatus("")
	}
	return b.Status
}
