// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type BatchReadInputSimplePublicObjectID struct {
	PropertiesWithHistory []string               `json:"propertiesWithHistory"`
	IDProperty            *string                `json:"idProperty,omitempty"`
	Inputs                []SimplePublicObjectID `json:"inputs"`
	Properties            []string               `json:"properties"`
}

func (o *BatchReadInputSimplePublicObjectID) GetPropertiesWithHistory() []string {
	if o == nil {
		return []string{}
	}
	return o.PropertiesWithHistory
}

func (o *BatchReadInputSimplePublicObjectID) GetIDProperty() *string {
	if o == nil {
		return nil
	}
	return o.IDProperty
}

func (o *BatchReadInputSimplePublicObjectID) GetInputs() []SimplePublicObjectID {
	if o == nil {
		return []SimplePublicObjectID{}
	}
	return o.Inputs
}

func (o *BatchReadInputSimplePublicObjectID) GetProperties() []string {
	if o == nil {
		return []string{}
	}
	return o.Properties
}
