// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BatchInputSimplePublicObjectInputForCreate struct {
	Inputs []SimplePublicObjectInputForCreate `json:"inputs"`
}

func (b *BatchInputSimplePublicObjectInputForCreate) GetInputs() []SimplePublicObjectInputForCreate {
	if b == nil {
		return []SimplePublicObjectInputForCreate{}
	}
	return b.Inputs
}
