// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BatchReadInputSimplePublicObjectID struct {
	PropertiesWithHistory []string               `json:"propertiesWithHistory"`
	IDProperty            *string                `json:"idProperty,omitempty"`
	Inputs                []SimplePublicObjectID `json:"inputs"`
	Properties            []string               `json:"properties"`
}

func (b *BatchReadInputSimplePublicObjectID) GetPropertiesWithHistory() []string {
	if b == nil {
		return []string{}
	}
	return b.PropertiesWithHistory
}

func (b *BatchReadInputSimplePublicObjectID) GetIDProperty() *string {
	if b == nil {
		return nil
	}
	return b.IDProperty
}

func (b *BatchReadInputSimplePublicObjectID) GetInputs() []SimplePublicObjectID {
	if b == nil {
		return []SimplePublicObjectID{}
	}
	return b.Inputs
}

func (b *BatchReadInputSimplePublicObjectID) GetProperties() []string {
	if b == nil {
		return []string{}
	}
	return b.Properties
}
