// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BatchInputSimplePublicObjectBatchInput struct {
	Inputs []SimplePublicObjectBatchInput `json:"inputs"`
}

func (b *BatchInputSimplePublicObjectBatchInput) GetInputs() []SimplePublicObjectBatchInput {
	if b == nil {
		return []SimplePublicObjectBatchInput{}
	}
	return b.Inputs
}
