// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type BatchInputSimplePublicObjectID struct {
	Inputs []SimplePublicObjectID `json:"inputs"`
}

func (o *BatchInputSimplePublicObjectID) GetInputs() []SimplePublicObjectID {
	if o == nil {
		return []SimplePublicObjectID{}
	}
	return o.Inputs
}
