// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CollectionResponseWithTotalSimplePublicObjectForwardPaging struct {
	Total   int                  `json:"total"`
	Paging  *ForwardPaging       `json:"paging,omitempty"`
	Results []SimplePublicObject `json:"results"`
}

func (c *CollectionResponseWithTotalSimplePublicObjectForwardPaging) GetTotal() int {
	if c == nil {
		return 0
	}
	return c.Total
}

func (c *CollectionResponseWithTotalSimplePublicObjectForwardPaging) GetPaging() *ForwardPaging {
	if c == nil {
		return nil
	}
	return c.Paging
}

func (c *CollectionResponseWithTotalSimplePublicObjectForwardPaging) GetResults() []SimplePublicObject {
	if c == nil {
		return []SimplePublicObject{}
	}
	return c.Results
}
