// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CollectionResponseAssociatedID struct {
	Paging  *Paging        `json:"paging,omitempty"`
	Results []AssociatedID `json:"results"`
}

func (c *CollectionResponseAssociatedID) GetPaging() *Paging {
	if c == nil {
		return nil
	}
	return c.Paging
}

func (c *CollectionResponseAssociatedID) GetResults() []AssociatedID {
	if c == nil {
		return []AssociatedID{}
	}
	return c.Results
}
