// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type CollectionResponseAssociatedID struct {
	Paging  *Paging        `json:"paging,omitempty"`
	Results []AssociatedID `json:"results"`
}

func (o *CollectionResponseAssociatedID) GetPaging() *Paging {
	if o == nil {
		return nil
	}
	return o.Paging
}

func (o *CollectionResponseAssociatedID) GetResults() []AssociatedID {
	if o == nil {
		return []AssociatedID{}
	}
	return o.Results
}
