// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CollectionResponseSimplePublicObjectWithAssociationsForwardPaging struct {
	Paging  *ForwardPaging                       `json:"paging,omitempty"`
	Results []SimplePublicObjectWithAssociations `json:"results"`
}

func (c *CollectionResponseSimplePublicObjectWithAssociationsForwardPaging) GetPaging() *ForwardPaging {
	if c == nil {
		return nil
	}
	return c.Paging
}

func (c *CollectionResponseSimplePublicObjectWithAssociationsForwardPaging) GetResults() []SimplePublicObjectWithAssociations {
	if c == nil {
		return []SimplePublicObjectWithAssociations{}
	}
	return c.Results
}
