// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type CollectionResponseWithTotalSimplePublicObjectForwardPaging struct {
	Total   int                  `json:"total"`
	Paging  *ForwardPaging       `json:"paging,omitempty"`
	Results []SimplePublicObject `json:"results"`
}

func (o *CollectionResponseWithTotalSimplePublicObjectForwardPaging) GetTotal() int {
	if o == nil {
		return 0
	}
	return o.Total
}

func (o *CollectionResponseWithTotalSimplePublicObjectForwardPaging) GetPaging() *ForwardPaging {
	if o == nil {
		return nil
	}
	return o.Paging
}

func (o *CollectionResponseWithTotalSimplePublicObjectForwardPaging) GetResults() []SimplePublicObject {
	if o == nil {
		return []SimplePublicObject{}
	}
	return o.Results
}
