// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ErrorDetail struct {
	// A specific category that contains more specific detail about the error
	SubCategory *string `json:"subCategory,omitempty"`
	// The status code associated with the error detail
	Code *string `json:"code,omitempty"`
	// The name of the field or parameter in which the error was found.
	In *string `json:"in,omitempty"`
	// Context about the error condition
	Context map[string][]string `json:"context,omitempty"`
	// A human readable message describing the error along with remediation steps where appropriate
	Message string `json:"message"`
}

func (o *ErrorDetail) GetSubCategory() *string {
	if o == nil {
		return nil
	}
	return o.SubCategory
}

func (o *ErrorDetail) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *ErrorDetail) GetIn() *string {
	if o == nil {
		return nil
	}
	return o.In
}

func (o *ErrorDetail) GetContext() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Context
}

func (o *ErrorDetail) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
