// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Error - An error occurred.
type Error struct {
	// A specific category that contains more specific detail about the error
	SubCategory *string
	// Context about the error condition
	Context map[string][]string
	// A unique identifier for the request. Include this value with any error reports or support tickets
	CorrelationID string
	// A map of link names to associated URIs containing documentation about the error or recommended remediation steps
	Links map[string]string
	// A human readable message describing the error along with remediation steps where appropriate
	Message string
	// The error category
	Category string
	// further information about the error
	Errors []ErrorDetail
}

func (e *Error) GetSubCategory() *string {
	if e == nil {
		return nil
	}
	return e.SubCategory
}

func (e *Error) GetContext() map[string][]string {
	if e == nil {
		return nil
	}
	return e.Context
}

func (e *Error) GetCorrelationID() string {
	if e == nil {
		return ""
	}
	return e.CorrelationID
}

func (e *Error) GetLinks() map[string]string {
	if e == nil {
		return nil
	}
	return e.Links
}

func (e *Error) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *Error) GetCategory() string {
	if e == nil {
		return ""
	}
	return e.Category
}

func (e *Error) GetErrors() []ErrorDetail {
	if e == nil {
		return nil
	}
	return e.Errors
}
