// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FilterGroup struct {
	Filters []Filter `json:"filters"`
}

func (f *FilterGroup) GetFilters() []Filter {
	if f == nil {
		return []Filter{}
	}
	return f.Filters
}
