// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type FilterGroup struct {
	Filters []Filter `json:"filters"`
}

func (o *FilterGroup) GetFilters() []Filter {
	if o == nil {
		return []Filter{}
	}
	return o.Filters
}
