// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ForwardPaging struct {
	Next *NextPage `json:"next,omitempty"`
}

func (f *ForwardPaging) GetNext() *NextPage {
	if f == nil {
		return nil
	}
	return f.Next
}
