// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ForwardPaging struct {
	Next *NextPage `json:"next,omitempty"`
}

func (o *ForwardPaging) GetNext() *NextPage {
	if o == nil {
		return nil
	}
	return o.Next
}
