// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type NextPage struct {
	Link  *string `json:"link,omitempty"`
	After string  `json:"after"`
}

func (o *NextPage) GetLink() *string {
	if o == nil {
		return nil
	}
	return o.Link
}

func (o *NextPage) GetAfter() string {
	if o == nil {
		return ""
	}
	return o.After
}
