// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NextPage struct {
	Link  *string `json:"link,omitempty"`
	After string  `json:"after"`
}

func (n *NextPage) GetLink() *string {
	if n == nil {
		return nil
	}
	return n.Link
}

func (n *NextPage) GetAfter() string {
	if n == nil {
		return ""
	}
	return n.After
}
