// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Paging struct {
	Next *NextPage     `json:"next,omitempty"`
	Prev *PreviousPage `json:"prev,omitempty"`
}

func (p *Paging) GetNext() *NextPage {
	if p == nil {
		return nil
	}
	return p.Next
}

func (p *Paging) GetPrev() *PreviousPage {
	if p == nil {
		return nil
	}
	return p.Prev
}
