// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PreviousPage struct {
	Before string  `json:"before"`
	Link   *string `json:"link,omitempty"`
}

func (p *PreviousPage) GetBefore() string {
	if p == nil {
		return ""
	}
	return p.Before
}

func (p *PreviousPage) GetLink() *string {
	if p == nil {
		return nil
	}
	return p.Link
}
