// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type PreviousPage struct {
	Before string  `json:"before"`
	Link   *string `json:"link,omitempty"`
}

func (o *PreviousPage) GetBefore() string {
	if o == nil {
		return ""
	}
	return o.Before
}

func (o *PreviousPage) GetLink() *string {
	if o == nil {
		return nil
	}
	return o.Link
}
