// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type PublicAssociationsForObject struct {
	Types []AssociationSpec `json:"types"`
	To    PublicObjectID    `json:"to"`
}

func (o *PublicAssociationsForObject) GetTypes() []AssociationSpec {
	if o == nil {
		return []AssociationSpec{}
	}
	return o.Types
}

func (o *PublicAssociationsForObject) GetTo() PublicObjectID {
	if o == nil {
		return PublicObjectID{}
	}
	return o.To
}
