// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type PublicMergeInput struct {
	ObjectIDToMerge string `json:"objectIdToMerge"`
	PrimaryObjectID string `json:"primaryObjectId"`
}

func (o *PublicMergeInput) GetObjectIDToMerge() string {
	if o == nil {
		return ""
	}
	return o.ObjectIDToMerge
}

func (o *PublicMergeInput) GetPrimaryObjectID() string {
	if o == nil {
		return ""
	}
	return o.PrimaryObjectID
}
