// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PublicObjectSearchRequest struct {
	Query        *string       `json:"query,omitempty"`
	Limit        int           `json:"limit"`
	After        string        `json:"after"`
	Sorts        []string      `json:"sorts"`
	Properties   []string      `json:"properties"`
	FilterGroups []FilterGroup `json:"filterGroups"`
}

func (p *PublicObjectSearchRequest) GetQuery() *string {
	if p == nil {
		return nil
	}
	return p.Query
}

func (p *PublicObjectSearchRequest) GetLimit() int {
	if p == nil {
		return 0
	}
	return p.Limit
}

func (p *PublicObjectSearchRequest) GetAfter() string {
	if p == nil {
		return ""
	}
	return p.After
}

func (p *PublicObjectSearchRequest) GetSorts() []string {
	if p == nil {
		return []string{}
	}
	return p.Sorts
}

func (p *PublicObjectSearchRequest) GetProperties() []string {
	if p == nil {
		return []string{}
	}
	return p.Properties
}

func (p *PublicObjectSearchRequest) GetFilterGroups() []FilterGroup {
	if p == nil {
		return []FilterGroup{}
	}
	return p.FilterGroups
}
