// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PublicAssociationsForObject struct {
	Types []AssociationSpec `json:"types"`
	To    PublicObjectID    `json:"to"`
}

func (p *PublicAssociationsForObject) GetTypes() []AssociationSpec {
	if p == nil {
		return []AssociationSpec{}
	}
	return p.Types
}

func (p *PublicAssociationsForObject) GetTo() PublicObjectID {
	if p == nil {
		return PublicObjectID{}
	}
	return p.To
}
