// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PublicMergeInput struct {
	ObjectIDToMerge string `json:"objectIdToMerge"`
	PrimaryObjectID string `json:"primaryObjectId"`
}

func (p *PublicMergeInput) GetObjectIDToMerge() string {
	if p == nil {
		return ""
	}
	return p.ObjectIDToMerge
}

func (p *PublicMergeInput) GetPrimaryObjectID() string {
	if p == nil {
		return ""
	}
	return p.PrimaryObjectID
}
