// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PublicObjectID struct {
	ID string `json:"id"`
}

func (p *PublicObjectID) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}
