// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PublicGdprDeleteInput struct {
	IDProperty *string `json:"idProperty,omitempty"`
	ObjectID   string  `json:"objectId"`
}

func (p *PublicGdprDeleteInput) GetIDProperty() *string {
	if p == nil {
		return nil
	}
	return p.IDProperty
}

func (p *PublicGdprDeleteInput) GetObjectID() string {
	if p == nil {
		return ""
	}
	return p.ObjectID
}
