// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type PublicObjectSearchRequest struct {
	Query        *string       `json:"query,omitempty"`
	Limit        int           `json:"limit"`
	After        string        `json:"after"`
	Sorts        []string      `json:"sorts"`
	Properties   []string      `json:"properties"`
	FilterGroups []FilterGroup `json:"filterGroups"`
}

func (o *PublicObjectSearchRequest) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *PublicObjectSearchRequest) GetLimit() int {
	if o == nil {
		return 0
	}
	return o.Limit
}

func (o *PublicObjectSearchRequest) GetAfter() string {
	if o == nil {
		return ""
	}
	return o.After
}

func (o *PublicObjectSearchRequest) GetSorts() []string {
	if o == nil {
		return []string{}
	}
	return o.Sorts
}

func (o *PublicObjectSearchRequest) GetProperties() []string {
	if o == nil {
		return []string{}
	}
	return o.Properties
}

func (o *PublicObjectSearchRequest) GetFilterGroups() []FilterGroup {
	if o == nil {
		return []FilterGroup{}
	}
	return o.FilterGroups
}
