// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Security struct {
	Oauth2 *string `security:"scheme,type=oauth2,name=Authorization"`
}

func (o *Security) GetOauth2() *string {
	if o == nil {
		return nil
	}
	return o.Oauth2
}
