// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SimplePublicObjectInput struct {
	Properties map[string]string `json:"properties"`
}

func (s *SimplePublicObjectInput) GetProperties() map[string]string {
	if s == nil {
		return map[string]string{}
	}
	return s.Properties
}
