// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type SimplePublicObjectID struct {
	ID string `json:"id"`
}

func (o *SimplePublicObjectID) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
