// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SimplePublicObjectID struct {
	ID string `json:"id"`
}

func (s *SimplePublicObjectID) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}
