// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type SimplePublicObjectBatchInput struct {
	IDProperty *string           `json:"idProperty,omitempty"`
	ID         string            `json:"id"`
	Properties map[string]string `json:"properties"`
}

func (o *SimplePublicObjectBatchInput) GetIDProperty() *string {
	if o == nil {
		return nil
	}
	return o.IDProperty
}

func (o *SimplePublicObjectBatchInput) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *SimplePublicObjectBatchInput) GetProperties() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Properties
}
