// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type SimplePublicObjectInputForCreate struct {
	Associations []PublicAssociationsForObject `json:"associations"`
	Properties   map[string]string             `json:"properties"`
}

func (o *SimplePublicObjectInputForCreate) GetAssociations() []PublicAssociationsForObject {
	if o == nil {
		return []PublicAssociationsForObject{}
	}
	return o.Associations
}

func (o *SimplePublicObjectInputForCreate) GetProperties() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Properties
}
