// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SimplePublicObjectBatchInput struct {
	IDProperty *string           `json:"idProperty,omitempty"`
	ID         string            `json:"id"`
	Properties map[string]string `json:"properties"`
}

func (s *SimplePublicObjectBatchInput) GetIDProperty() *string {
	if s == nil {
		return nil
	}
	return s.IDProperty
}

func (s *SimplePublicObjectBatchInput) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SimplePublicObjectBatchInput) GetProperties() map[string]string {
	if s == nil {
		return map[string]string{}
	}
	return s.Properties
}
