// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"github.com/speakeasy-sdks/hubspot-go/deals/internal/utils"
	"time"
)

type SimplePublicObject struct {
	CreatedAt             time.Time                       `json:"createdAt"`
	Archived              *bool                           `json:"archived,omitempty"`
	ArchivedAt            *time.Time                      `json:"archivedAt,omitempty"`
	PropertiesWithHistory map[string][]ValueWithTimestamp `json:"propertiesWithHistory,omitempty"`
	ID                    string                          `json:"id"`
	Properties            map[string]string               `json:"properties"`
	UpdatedAt             time.Time                       `json:"updatedAt"`
}

func (s SimplePublicObject) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SimplePublicObject) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SimplePublicObject) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *SimplePublicObject) GetArchived() *bool {
	if o == nil {
		return nil
	}
	return o.Archived
}

func (o *SimplePublicObject) GetArchivedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ArchivedAt
}

func (o *SimplePublicObject) GetPropertiesWithHistory() map[string][]ValueWithTimestamp {
	if o == nil {
		return nil
	}
	return o.PropertiesWithHistory
}

func (o *SimplePublicObject) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *SimplePublicObject) GetProperties() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Properties
}

func (o *SimplePublicObject) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
