// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/speakeasy-sdks/hubspot-go/deals/internal/utils"
	"time"
)

type SimplePublicObject struct {
	CreatedAt             time.Time                       `json:"createdAt"`
	Archived              *bool                           `json:"archived,omitempty"`
	ArchivedAt            *time.Time                      `json:"archivedAt,omitempty"`
	PropertiesWithHistory map[string][]ValueWithTimestamp `json:"propertiesWithHistory,omitempty"`
	ID                    string                          `json:"id"`
	Properties            map[string]*string              `json:"properties"`
	UpdatedAt             time.Time                       `json:"updatedAt"`
}

func (s SimplePublicObject) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SimplePublicObject) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"createdAt", "id", "properties", "updatedAt"}); err != nil {
		return err
	}
	return nil
}

func (s *SimplePublicObject) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *SimplePublicObject) GetArchived() *bool {
	if s == nil {
		return nil
	}
	return s.Archived
}

func (s *SimplePublicObject) GetArchivedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.ArchivedAt
}

func (s *SimplePublicObject) GetPropertiesWithHistory() map[string][]ValueWithTimestamp {
	if s == nil {
		return nil
	}
	return s.PropertiesWithHistory
}

func (s *SimplePublicObject) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SimplePublicObject) GetProperties() map[string]*string {
	if s == nil {
		return map[string]*string{}
	}
	return s.Properties
}

func (s *SimplePublicObject) GetUpdatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.UpdatedAt
}
