// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/speakeasy-sdks/hubspot-go/deals/internal/utils"
	"time"
)

type SimplePublicObjectWithAssociations struct {
	Associations          map[string]CollectionResponseAssociatedID `json:"associations,omitempty"`
	CreatedAt             time.Time                                 `json:"createdAt"`
	Archived              *bool                                     `json:"archived,omitempty"`
	ArchivedAt            *time.Time                                `json:"archivedAt,omitempty"`
	PropertiesWithHistory map[string][]ValueWithTimestamp           `json:"propertiesWithHistory,omitempty"`
	ID                    string                                    `json:"id"`
	Properties            map[string]*string                        `json:"properties"`
	UpdatedAt             time.Time                                 `json:"updatedAt"`
}

func (s SimplePublicObjectWithAssociations) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SimplePublicObjectWithAssociations) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"createdAt", "id", "properties", "updatedAt"}); err != nil {
		return err
	}
	return nil
}

func (s *SimplePublicObjectWithAssociations) GetAssociations() map[string]CollectionResponseAssociatedID {
	if s == nil {
		return nil
	}
	return s.Associations
}

func (s *SimplePublicObjectWithAssociations) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *SimplePublicObjectWithAssociations) GetArchived() *bool {
	if s == nil {
		return nil
	}
	return s.Archived
}

func (s *SimplePublicObjectWithAssociations) GetArchivedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.ArchivedAt
}

func (s *SimplePublicObjectWithAssociations) GetPropertiesWithHistory() map[string][]ValueWithTimestamp {
	if s == nil {
		return nil
	}
	return s.PropertiesWithHistory
}

func (s *SimplePublicObjectWithAssociations) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SimplePublicObjectWithAssociations) GetProperties() map[string]*string {
	if s == nil {
		return map[string]*string{}
	}
	return s.Properties
}

func (s *SimplePublicObjectWithAssociations) GetUpdatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.UpdatedAt
}
