// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SimplePublicObjectInputForCreate struct {
	Associations []PublicAssociationsForObject `json:"associations"`
	Properties   map[string]string             `json:"properties"`
}

func (s *SimplePublicObjectInputForCreate) GetAssociations() []PublicAssociationsForObject {
	if s == nil {
		return []PublicAssociationsForObject{}
	}
	return s.Associations
}

func (s *SimplePublicObjectInputForCreate) GetProperties() map[string]string {
	if s == nil {
		return map[string]string{}
	}
	return s.Properties
}
