// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type SubCategory struct {
}

type StandardError struct {
	SubCategory *SubCategory        `json:"subCategory,omitempty"`
	Context     map[string][]string `json:"context"`
	Links       map[string]string   `json:"links"`
	ID          *string             `json:"id,omitempty"`
	Category    string              `json:"category"`
	Message     string              `json:"message"`
	Errors      []ErrorDetail       `json:"errors"`
	Status      string              `json:"status"`
}

func (o *StandardError) GetSubCategory() *SubCategory {
	if o == nil {
		return nil
	}
	return o.SubCategory
}

func (o *StandardError) GetContext() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Context
}

func (o *StandardError) GetLinks() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Links
}

func (o *StandardError) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *StandardError) GetCategory() string {
	if o == nil {
		return ""
	}
	return o.Category
}

func (o *StandardError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *StandardError) GetErrors() []ErrorDetail {
	if o == nil {
		return []ErrorDetail{}
	}
	return o.Errors
}

func (o *StandardError) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}
