// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SubCategory struct {
}

type StandardError struct {
	SubCategory *SubCategory        `json:"subCategory,omitempty"`
	Context     map[string][]string `json:"context"`
	Links       map[string]string   `json:"links"`
	ID          *string             `json:"id,omitempty"`
	Category    string              `json:"category"`
	Message     string              `json:"message"`
	Errors      []ErrorDetail       `json:"errors"`
	Status      string              `json:"status"`
}

func (s *StandardError) GetSubCategory() *SubCategory {
	if s == nil {
		return nil
	}
	return s.SubCategory
}

func (s *StandardError) GetContext() map[string][]string {
	if s == nil {
		return map[string][]string{}
	}
	return s.Context
}

func (s *StandardError) GetLinks() map[string]string {
	if s == nil {
		return map[string]string{}
	}
	return s.Links
}

func (s *StandardError) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *StandardError) GetCategory() string {
	if s == nil {
		return ""
	}
	return s.Category
}

func (s *StandardError) GetMessage() string {
	if s == nil {
		return ""
	}
	return s.Message
}

func (s *StandardError) GetErrors() []ErrorDetail {
	if s == nil {
		return []ErrorDetail{}
	}
	return s.Errors
}

func (s *StandardError) GetStatus() string {
	if s == nil {
		return ""
	}
	return s.Status
}
