// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/speakeasy-sdks/hubspot-go/deals/internal/utils"
	"time"
)

type ValueWithTimestamp struct {
	SourceID        *string   `json:"sourceId,omitempty"`
	SourceType      string    `json:"sourceType"`
	SourceLabel     *string   `json:"sourceLabel,omitempty"`
	UpdatedByUserID *int      `json:"updatedByUserId,omitempty"`
	Value           string    `json:"value"`
	Timestamp       time.Time `json:"timestamp"`
}

func (v ValueWithTimestamp) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *ValueWithTimestamp) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"sourceType", "value", "timestamp"}); err != nil {
		return err
	}
	return nil
}

func (v *ValueWithTimestamp) GetSourceID() *string {
	if v == nil {
		return nil
	}
	return v.SourceID
}

func (v *ValueWithTimestamp) GetSourceType() string {
	if v == nil {
		return ""
	}
	return v.SourceType
}

func (v *ValueWithTimestamp) GetSourceLabel() *string {
	if v == nil {
		return nil
	}
	return v.SourceLabel
}

func (v *ValueWithTimestamp) GetUpdatedByUserID() *int {
	if v == nil {
		return nil
	}
	return v.UpdatedByUserID
}

func (v *ValueWithTimestamp) GetValue() string {
	if v == nil {
		return ""
	}
	return v.Value
}

func (v *ValueWithTimestamp) GetTimestamp() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.Timestamp
}
