// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"github.com/speakeasy-sdks/hubspot-go/deals/internal/utils"
	"time"
)

type ValueWithTimestamp struct {
	SourceID        *string   `json:"sourceId,omitempty"`
	SourceType      string    `json:"sourceType"`
	SourceLabel     *string   `json:"sourceLabel,omitempty"`
	UpdatedByUserID *int      `json:"updatedByUserId,omitempty"`
	Value           string    `json:"value"`
	Timestamp       time.Time `json:"timestamp"`
}

func (v ValueWithTimestamp) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *ValueWithTimestamp) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ValueWithTimestamp) GetSourceID() *string {
	if o == nil {
		return nil
	}
	return o.SourceID
}

func (o *ValueWithTimestamp) GetSourceType() string {
	if o == nil {
		return ""
	}
	return o.SourceType
}

func (o *ValueWithTimestamp) GetSourceLabel() *string {
	if o == nil {
		return nil
	}
	return o.SourceLabel
}

func (o *ValueWithTimestamp) GetUpdatedByUserID() *int {
	if o == nil {
		return nil
	}
	return o.UpdatedByUserID
}

func (o *ValueWithTimestamp) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}

func (o *ValueWithTimestamp) GetTimestamp() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Timestamp
}
