workflowVersion: 1.0.0
sources:
    deals:
        inputs:
            - location: https://api.hubspot.com/api-catalog-public/v1/apis/crm/v3/objects/deals
targets:
    deals:
        target: go
        source: deals
        output: ./deals
